# Notes - Xarray

## Terminology

- DataArray: A multi-dimensional array with labeled or named dimensions. DataArray objects add metadata such as dimension names, coordinates, and attributes. For example, an array is var(time, level, lat, lon).
- DataSet: A dict-like collection of DataArray objects with aligned dimensions. For example, a dataset contains temperature(time, level, lat, lon) and precipitation(time, lat, lon).

## References

- Unidata Xarray Introduction, https://unidata.github.io/python-training/workshop/XArray/xarray-introduction/
- Xarray quick overview, https://docs.xarray.dev/en/stable/getting-started-guide/quick-overview.html
- Xarray computation, https://docs.xarray.dev/en/stable/user-guide/computation.html


In [2]:
import numpy as np
import xarray as xr
import io, os, sys, types
import yhc_module as yhc

## Create and Modify a DataArray

### Create a DataArray

Xarray - https://docs.xarray.dev/en/stable/getting-started-guide/quick-overview.html#create-a-dataarray

Unidata - https://unidata.github.io/python-training/workshop/XArray/xarray-introduction/#DataArray

In [3]:
#--- Create some sample "temperature" data
data = 283 + 5 * np.random.randn(5, 3, 4)

time = np.arange(0,5)
lat = np.linspace(-120., 60., 3)
lon = np.linspace(25.,55.,4)

#--- create a DataArray & set attributes
temp = xr.DataArray(data, dims=['time', 'lat', 'lon'], coords=[time, lat, lon])

temp.attrs['units'] = "K"
temp.attrs['long_name'] = "Temperature"

with xr.set_options(keep_attrs=True):  # keep attributes after operation
  temp_degC = temp - 273.15
temp_degC.attrs['units'] = "C"
yhc.printv(temp_degC, "temp_degC")

#--- put all in one line
arr = xr.DataArray(np.random.RandomState(0).randn(2, 3), [("x", ["a", "b"]), ("y", [10, 20, 30])])
yhc.printv(arr, "arr")


 ------------- 
 temp_degC
<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[ 4.95925293, 10.12887717, 12.89690182,  7.32318775],
        [ 7.47226909,  9.76679759,  1.64497371,  3.44413595],
        [-1.2506204 ,  4.08891667, 13.30317399, 14.75724353]],

       [[13.8776665 ,  6.63885734,  8.39220479, -0.13782343],
        [10.76251095,  9.40931121,  0.13741138, 10.56832778],
        [11.21722757, 11.81472299,  9.14024419,  9.67082787]],

       [[11.38961201, 17.76039756, 17.33376534,  2.82173808],
        [ 7.26532689,  8.88522086,  6.27061857, 15.62635172],
        [ 9.32746003, 14.18384839, 10.44034653, 13.94431165]],

       [[ 8.13022179, 16.89485778,  7.29855359,  5.59233724],
        [ 9.74501788, 10.24380799, 10.87123464,  5.34654718],
        [ 1.99357042, 11.71243554,  6.04450741, 13.94458267]],

       [[ 4.99503482, 13.68490396,  7.60550357, 10.05650252],
        [18.89775548,  4.84327704, 15.97253952, 11.38073498],
        [10.81365694, 17.1372384 , 11.30575325,  9.1

### Copy from an exisitng DataArray

In [4]:
#--- create a sample array
arr0 = xr.DataArray(np.random.RandomState(0).randn(2, 3), [("x", ["a", "b"]), ("y", [10, 20, 30])])
yhc.printv(arr0,'original arr0')

#--- arr1 = arr0, I think this means arr1 and arr0 share the same memory. 
#    So if you change arr1, arr0 is automatically changed as well. 
arr1 = arr0
arr1[0,0] = 100.
arr1[1,1] = 50.
arr2 = arr1 - arr0      # arr1 still equal to arr0, even though I have already change the values...
yhc.printv(arr1,'arr0')
yhc.printv(arr1,'arr1')
yhc.printv(arr2,'arr2')

#--- use copy() to make a copy of an existing DataArray.
arrA = arr0.copy()
arrA[0,0] = 75.
arrA[1,1] = 30.
arrB = arrA - arr0
yhc.printv(arr0,'arr0')
yhc.printv(arrA,'arrA')
yhc.printv(arrB,'arrB')

#--- copy an existing dataArray and reset all elements to zeros
arrC = arr0.copy().where(arr0 == 0., 0., 0.)
# Cannot use arrC = 0., This will return arrC = 0.
yhc.printv(arrC,'arrC')

 ------------- 
 original arr0
<xarray.DataArray (x: 2, y: 3)>
array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

 ------------- 
 arr0
<xarray.DataArray (x: 2, y: 3)>
array([[100.        ,   0.40015721,   0.97873798],
       [  2.2408932 ,  50.        ,  -0.97727788]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

 ------------- 
 arr1
<xarray.DataArray (x: 2, y: 3)>
array([[100.        ,   0.40015721,   0.97873798],
       [  2.2408932 ,  50.        ,  -0.97727788]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

 ------------- 
 arr2
<xarray.DataArray (x: 2, y: 3)>
array([[0., 0., 0.],
       [0., 0., 0.]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

 ------------- 
 arr0
<xarray.DataArray (x: 2, y: 3)>
array([[100.        ,   0.40015721,   0.97873798],
       [  2.2408932 ,  5

### Modify coordinates of a DataArray

Xarray, modify coordinates
https://docs.xarray.dev/en/stable/generated/xarray.Dataset.assign_coords.html

In [5]:
#--- create a sample
arr = xr.DataArray(np.random.RandomState(0).randn(2, 3), [("x", ["a", "b"]), ("y", [10, 20, 30])])
yhc.printv(arr, "original")

#--- print out coordinate
arr.coords["x"]   # print out coordinate "x" values

#--- assign completely new coordinate values
x_new = ["cc","dd"]
arr = arr.assign_coords({"x":x_new}) # modidy the arraymodify "x" coordinate from [a,b] to [c,d]
    #arr.assign_coords({"x":x_new})    # This will show new coordinate but not modidy the array
yhc.printv(arr,"modify x")

#--- arthemetric operation of exisitng coordiate values
arr.assign_coords(y=arr.y+1)   # modify the coordinate values
arr = arr.assign_coords(y=((arr.y+5)/2)+1.)
yhc.printv(arr,"modify y")

#--- put all in one line
arr = arr.assign_coords({"x":["ee","ff"], "y":arr.y+1})
yhc.printv(arr, "modify x and y")

#--- change coordinate names
arr = arr.rename({"x":"x2", "y":"y2"})  # rename coordinate
yhc.printv(arr, 'rename')

#--- New coordinate can also be attached to an existing dimension
y_new = [11,12,13]
arr = arr.assign_coords(y_new=("y2", y_new))
yhc.printv(arr, 'add y_new as a coordinate variable')

#--- Add a new coordinate and the original array would be expanded 
z = np.array([1,2,3,4])
arr = arr.expand_dims(z=z)   # add a new coordinate "z". The "z" values are np.arrry *z*.
yhc.printv(arr, "add a new z coordiate")


 ------------- 
 original
<xarray.DataArray (x: 2, y: 3)>
array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

 ------------- 
 modify x
<xarray.DataArray (x: 2, y: 3)>
array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788]])
Coordinates:
  * x        (x) <U2 'cc' 'dd'
  * y        (y) int64 10 20 30

 ------------- 
 modify y
<xarray.DataArray (x: 2, y: 3)>
array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788]])
Coordinates:
  * x        (x) <U2 'cc' 'dd'
  * y        (y) float64 8.5 13.5 18.5

 ------------- 
 modify x and y
<xarray.DataArray (x: 2, y: 3)>
array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788]])
Coordinates:
  * x        (x) <U2 'ee' 'ff'
  * y        (y) float64 9.5 14.5 19.5

 ------------- 
 rename
<xarray.DataArray (x2: 2, y2: 

## Selection

Unidata - https://unidata.github.io/python-training/workshop/XArray/xarray-introduction/#Selection

### Selection Method 1: use indexing

In [5]:
#--- Method 1: use indexing
var = temp[0, 1:2, :]
var

<xarray.DataArray (lat: 1, lon: 4)>
array([[285.86984984, 280.15845844, 282.16670022, 272.13967216]])
Coordinates:
    time     int64 0
  * lat      (lat) float64 -30.0
  * lon      (lon) float64 25.0 35.0 45.0 55.0
Attributes:
    units:      K
    long_name:  Temperature

### Selection Method 2: Use name dimension & slicing

In [6]:
#--- Method 2; use name dimension
temp.coords  # check out variable dimension
print(temp.coords)

#--- select specific values in coordinates
var = temp.sel(time=1, lat=-30., lon=25)
var = temp.sel(time=1, lat=-30.2, lon=25.3, method='nearest')

print('------------')
print(var)

var = temp.sel(time=1, lon=25)
print('------------')
print(var)

#--- Slicing with Selection
var = temp.sel(time=slice(0,2), lat=-30., lon=slice(-1000.,1000.))
print('------------')
print(var)

Coordinates:
  * time     (time) int64 0 1 2 3 4
  * lat      (lat) float64 -120.0 -30.0 60.0
  * lon      (lon) float64 25.0 35.0 45.0 55.0
------------
<xarray.DataArray ()>
array(275.24283659)
Coordinates:
    time     int64 1
    lat      float64 -30.0
    lon      float64 25.0
Attributes:
    units:      K
    long_name:  Temperature
------------
<xarray.DataArray (lat: 3)>
array([282.92220954, 275.24283659, 276.82457973])
Coordinates:
    time     int64 1
  * lat      (lat) float64 -120.0 -30.0 60.0
    lon      float64 25.0
Attributes:
    units:      K
    long_name:  Temperature
------------
<xarray.DataArray (time: 3, lon: 4)>
array([[285.86984984, 280.15845844, 282.16670022, 272.13967216],
       [275.24283659, 278.82022433, 284.41629301, 278.3160379 ],
       [289.88599235, 290.35154018, 281.18520171, 282.09600708]])
Coordinates:
  * time     (time) int64 0 1 2
    lat      float64 -30.0
  * lon      (lon) float64 25.0 35.0 45.0 55.0
Attributes:
    units:      K
    long_n

### Selection Method 3: use .loc

In [7]:
#*** Useful if already knowing the range to each coordinate

# temp is temp(time, lat, lon)
var = temp.loc[0:4, -120:30, :]
print(var)

<xarray.DataArray (time: 5, lat: 2, lon: 4)>
array([[[278.03790293, 276.49354584, 283.02837148, 285.13368382],
        [285.86984984, 280.15845844, 282.16670022, 272.13967216]],

       [[282.92220954, 285.6184446 , 288.06330279, 284.71532408],
        [275.24283659, 278.82022433, 284.41629301, 278.3160379 ]],

       [[283.95940436, 277.43493053, 288.65227031, 280.34818867],
        [289.88599235, 290.35154018, 281.18520171, 282.09600708]],

       [[281.66910418, 278.84651983, 283.5268632 , 281.32496876],
        [278.50537002, 276.02551073, 288.63638866, 286.93822403]],

       [[282.03173239, 279.87526553, 271.48742204, 281.29918993],
        [289.82540408, 284.27550714, 276.23870253, 284.91084743]]])
Coordinates:
  * time     (time) int64 0 1 2 3 4
  * lat      (lat) float64 -120.0 -30.0
  * lon      (lon) float64 25.0 35.0 45.0 55.0
Attributes:
    units:      K
    long_name:  Temperature


### Selection Method 4: where() to conditionally switch between values

In [8]:
#--- use where()
var = temp.where(temp > 280.)  # if temp < 280., it would become nan
var

#--- create a mask, but fail.
#xr.where(temp > 280., "positive", "negative")

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[         nan,          nan, 283.02837148, 285.13368382],
        [285.86984984, 280.15845844, 282.16670022,          nan],
        [283.91619513, 286.47137273, 288.82654058,          nan]],

       [[282.92220954, 285.6184446 , 288.06330279, 284.71532408],
        [         nan,          nan, 284.41629301,          nan],
        [         nan,          nan, 280.07643958, 281.67930977]],

       [[283.95940436,          nan, 288.65227031, 280.34818867],
        [289.88599235, 290.35154018, 281.18520171, 282.09600708],
        [         nan, 289.90213372, 285.2802876 , 282.15711226]],

       [[281.66910418,          nan, 283.5268632 , 281.32496876],
        [         nan,          nan, 288.63638866, 286.93822403],
        [281.4252234 , 287.06417483, 280.29009705, 287.1194597 ]],

       [[282.03173239,          nan,          nan, 281.29918993],
        [289.82540408, 284.27550714,          nan, 284.91084743],
        [         nan,          nan, 295.01425001, 288.07119728]]])
Coordinates:
  * time     (time) int64 0 1 2 3 4
  * lat      (lat) float64 -120.0 -30.0 60.0
  * lon      (lon) float64 25.0 35.0 45.0 55.0
Attributes:
    units:      K
    long_name:  Temperature

## Reshaping and reorganizing data

### Reordering dimensions, Expand/Squeeze data
https://docs.xarray.dev/en/stable/user-guide/reshaping.html#reordering-dimensions

In [9]:
#--- create a sample
ds = xr.Dataset({"foo": (("x", "y", "z"), [[[42]]]), "bar": (("y", "z"), [[24]])})
yhc.printv(ds,'original')

#--- reorder dimensions of all variables
ds1 = ds.transpose("y", "z", "x")
    #ds.transpose()          # reverses all dimensions
    #ds.transpose(..., "x")  # move "x" to the last dimension
yhc.printv(ds1,'reorder dims')

#--- expand data
ds_expand = ds.expand_dims(w=np.zeros(2))
yhc.printv(ds_expand, "expand dims")

#--- squeeze data
ds_squeeze = ds.squeeze("x")
yhc.printv(ds_squeeze, "squeeze dims")

 ------------- 
 original
<xarray.Dataset>
Dimensions:  (x: 1, y: 1, z: 1)
Dimensions without coordinates: x, y, z
Data variables:
    foo      (x, y, z) int64 42
    bar      (y, z) int64 24

 ------------- 
 reorder dims
<xarray.Dataset>
Dimensions:  (x: 1, y: 1, z: 1)
Dimensions without coordinates: x, y, z
Data variables:
    foo      (y, z, x) int64 42
    bar      (y, z) int64 24

 ------------- 
 expand dims
<xarray.Dataset>
Dimensions:  (x: 1, y: 1, z: 1, w: 2)
Coordinates:
  * w        (w) float64 0.0 0.0
Dimensions without coordinates: x, y, z
Data variables:
    foo      (w, x, y, z) int64 42 42
    bar      (w, y, z) int64 24 24

 ------------- 
 squeeze dims
<xarray.Dataset>
Dimensions:  (y: 1, z: 1)
Dimensions without coordinates: y, z
Data variables:
    foo      (y, z) int64 42
    bar      (y, z) int64 24



### Converting between datasets and arrays
https://docs.xarray.dev/en/stable/user-guide/reshaping.html#converting-between-datasets-and-arrays


In [10]:
#--- convert between a Dataset and a DataArray. All variables will be on a new dimension, variable
arr = ds.to_array()
yhc.printv(ds, 'Dataset')
yhc.printv(arr, 'DataArray')

ds1 = arr.to_dataset(dim="variable")
yhc.printv(ds1, 'Back to Dataset')


 ------------- 
 Dataset
<xarray.Dataset>
Dimensions:  (x: 1, y: 1, z: 1)
Dimensions without coordinates: x, y, z
Data variables:
    foo      (x, y, z) int64 42
    bar      (y, z) int64 24

 ------------- 
 DataArray
<xarray.DataArray (variable: 2, x: 1, y: 1, z: 1)>
array([[[[42]]],


       [[[24]]]])
Coordinates:
  * variable  (variable) <U3 'foo' 'bar'
Dimensions without coordinates: x, y, z

 ------------- 
 Back to Dataset
<xarray.Dataset>
Dimensions:  (x: 1, y: 1, z: 1)
Dimensions without coordinates: x, y, z
Data variables:
    foo      (x, y, z) int64 42
    bar      (x, y, z) int64 24



### Stack and unstack
https://docs.xarray.dev/en/stable/user-guide/reshaping.html#stack-and-unstack

In [11]:
#--- create a sample DataArray
arr = xr.DataArray(np.random.randn(2, 3), coords=[("x", ["a", "b"]), ("y", [0, 1, 2])])

#--- stack the array
arr_z = arr.stack(z=("x","y"))

#--- unstack the array
arr_unstack = arr_z.unstack("z")

yhc.printv(arr, 'original')
yhc.printv(arr_z, 'merge x,y dims to z')
yhc.printv(arr_unstack, 'unstack z')

 ------------- 
 original
<xarray.DataArray (x: 2, y: 3)>
array([[-0.06778145,  0.16801941,  1.54893101],
       [ 0.55350895,  1.38461153, -0.64156218]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 0 1 2

 ------------- 
 merge x,y dims to z
<xarray.DataArray (z: 6)>
array([-0.06778145,  0.16801941,  1.54893101,  0.55350895,  1.38461153,
       -0.64156218])
Coordinates:
  * z        (z) MultiIndex
  - x        (z) object 'a' 'a' 'a' 'b' 'b' 'b'
  - y        (z) int64 0 1 2 0 1 2

 ------------- 
 unstack z
<xarray.DataArray (x: 2, y: 3)>
array([[-0.06778145,  0.16801941,  1.54893101],
       [ 0.55350895,  1.38461153, -0.64156218]])
Coordinates:
  * x        (x) object 'a' 'b'
  * y        (y) int64 0 1 2



## Save variables to a new netCDF file

- Saving Datasets and DataArrays to NetCDF, https://ecco-v4-python-tutorial.readthedocs.io/ECCO_v4_Saving_Datasets_and_DataArrays_to_NetCDF.html

### Merge multiple DataArray to a DataSet

In [21]:
#--- Create two DataArray, var1 & var2
x = np.linspace(-10,10,10)
y = np.linspace(-20,20,20)
(yy, xx) = np.meshgrid(y,x)

var1 = xr.DataArray(np.random.randn(len(x),len(y)),coords=[x, y],dims=['x','y'])
var2 = xr.DataArray(np.random.randn(len(x)),coords=[x],dims=['x'])

var1.attrs['long_name'] = "var1"
var1.attrs['units'] = "KK"

var2.attrs['long_name'] = "var2"
var2.attrs['units'] = "PP"

#--- convert var1 to a dataset
ds = var1.to_dataset(name = 'varA')
ds.attrs["contact"] = "yihsuan"   # set global attribute

#--- save var2 into the dataset
ds['varB'] = var2

ds

<xarray.Dataset>
Dimensions:  (x: 10, y: 20)
Coordinates:
  * x        (x) float64 -10.0 -7.778 -5.556 -3.333 ... 3.333 5.556 7.778 10.0
  * y        (y) float64 -20.0 -17.89 -15.79 -13.68 ... 13.68 15.79 17.89 20.0
Data variables:
    varA     (x, y) float64 0.6159 0.823 -1.034 ... -0.2889 -0.1293 -1.188
    varB     (x) float64 0.7533 -0.3444 -0.7102 0.1949 ... -0.7233 0.5365 0.1892
Attributes:
    contact:  yihsuan

### Save the Dataset to a new netCDF file

In [19]:
new_filename = "./test111.nc"

ds.to_netcdf(path=new_filename)
ds.close()

ds1 = xr.open_dataset(new_filename)
ds1


PermissionError: [Errno 13] Permission denied: b'/Users/yihsuan/Downloads/yihsuan/test/tool/python/yhc_module_and_notes/test111.nc'

## Computation &

### Basic numerical operation

In [14]:
#--- arithmetic operation
xr.set_options(keep_attrs =True)  # keep attributes after operations
temp_degC = temp - 273.15
temp_degC.attrs['units']="C"
temp_degC

#--- mean and others
#    a list: mean, min, max, std, sum, weighted
temp_tavg = temp.mean("time")
temp_tavg

temp_tiavg = temp.mean(["time","lon"])
temp_tiavg

<xarray.DataArray (lat: 3)>
array([281.72343224, 282.30023842, 282.72410903])
Coordinates:
  * lat      (lat) float64 -120.0 -30.0 60.0
Attributes:
    units:      K
    long_name:  Temperature

### Rolling average

https://xarray.pydata.org/en/stable/user-guide/computation.html#rolling-window-operations
https://xarray.pydata.org/en/stable/generated/xarray.DataArray.rolling.html#xarray.DataArray.rolling

In [15]:
  #--- pk values. Output directly from AM4 files
  pk_list = [100, 400, 818.6021, 1378.886, 2091.795, 2983.641, 4121.79, 5579.222, 
    6907.19, 7735.787, 8197.665, 8377.955, 8331.696, 8094.722, 7690.857, 
    7139.018, 6464.803, 5712.357, 4940.054, 4198.604, 3516.633, 2905.199, 
    2366.737, 1899.195, 1497.781, 1156.253, 867.792, 625.5933, 426.2132, 
    264.7661, 145.0665, 60, 15, 0]

  #--- bk values. Output directly from AM4 files
  bk_list = [0, 0, 0, 0, 0, 0, 0, 0, 0.00513, 0.01969, 0.04299, 0.07477, 0.11508, 
    0.16408, 0.22198, 0.28865, 0.36281, 0.44112, 0.51882, 0.59185, 0.6581, 
    0.71694, 0.76843, 0.81293, 0.851, 0.88331, 0.91055, 0.93331, 0.95214, 
    0.9675, 0.97968, 0.98908, 0.99575, 1]  

  #--- make DataArray
  ps = xr.DataArray([102000.], dims=['time'])
  pk = xr.DataArray(pk_list, dims=['plev'])
  bk = xr.DataArray(bk_list, dims=['plev'])

  #--- p at half levels: p = ps*bk + pk. ps is the first term because it would be broadcasted.
  phalf = ps*bk + pk

  #--- compute p at full levels, using .rolling(). NaNs is removed by dropna()
  pfull = phalf.rolling(plev=2, center=True).mean().dropna("plev")
  yhc.printv(phalf, "phalf")
  yhc.printv(pfull, "pfull")

 ------------- 
 phalf
<xarray.DataArray (time: 1, plev: 34)>
array([[1.00000000e+02, 4.00000000e+02, 8.18602100e+02, 1.37888600e+03,
        2.09179500e+03, 2.98364100e+03, 4.12179000e+03, 5.57922200e+03,
        7.43045000e+03, 9.74416700e+03, 1.25826450e+04, 1.60044950e+04,
        2.00698560e+04, 2.48308820e+04, 3.03328170e+04, 3.65813180e+04,
        4.34714230e+04, 5.07065970e+04, 5.78596940e+04, 6.45673040e+04,
        7.06428330e+04, 7.60330790e+04, 8.07465970e+04, 8.48180550e+04,
        8.82997810e+04, 9.12538730e+04, 9.37438920e+04, 9.58232133e+04,
        9.75444932e+04, 9.89497661e+04, 1.00072427e+05, 1.00946160e+05,
        1.01581500e+05, 1.02000000e+05]])
Dimensions without coordinates: time, plev

 ------------- 
 pfull
<xarray.DataArray (time: 1, plev: 33)>
array([[   250.     ,    609.30105,   1098.74405,   1735.3405 ,
          2537.718  ,   3552.7155 ,   4850.506  ,   6504.836  ,
          8587.3085 ,  11163.406  ,  14293.57   ,  18037.1755 ,
         22450.369  , 

### Broadcasting by dimension name

https://docs.xarray.dev/en/stable/user-guide/computation.html#broadcasting-by-dimension-name

In [16]:
a = xr.DataArray([1, 2], [("x", ["a", "b"])])
b = xr.DataArray([-1, -2, -3], [("y", [10, 20, 30])])
c = xr.DataArray(np.arange(6).reshape(3, 2), [b["y"], a["x"]])

#print(a)
#print(b)
#print(c)

#--- With xarray, and their dimensions are expanded automatically:
print(a*b)  # 2x3 array
print(b*a)  # 3x2 array

#--- explicitly broadcast xarray data structures by using the broadcast()
a2, b2 = xr.broadcast(a, b)
print(a2)
print(b2)


<xarray.DataArray (x: 2, y: 3)>
array([[-1, -2, -3],
       [-2, -4, -6]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30
<xarray.DataArray (y: 3, x: 2)>
array([[-1, -2],
       [-2, -4],
       [-3, -6]])
Coordinates:
  * y        (y) int64 10 20 30
  * x        (x) <U1 'a' 'b'
<xarray.DataArray (x: 2, y: 3)>
array([[1, 1, 1],
       [2, 2, 2]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30
<xarray.DataArray (x: 2, y: 3)>
array([[-1, -2, -3],
       [-1, -2, -3]])
Coordinates:
  * y        (y) int64 10 20 30
  * x        (x) <U1 'a' 'b'


### Automatic alignment
https://docs.xarray.dev/en/stable/user-guide/computation.html#automatic-alignment



In [17]:
arr = xr.DataArray(np.arange(3), [("x", range(3))])

#--- only operate available elements
print(arr)
print(arr[:-1])
print(arr + arr[:-1])

<xarray.DataArray (x: 3)>
array([0, 1, 2])
Coordinates:
  * x        (x) int64 0 1 2
<xarray.DataArray (x: 2)>
array([0, 1])
Coordinates:
  * x        (x) int64 0 1
<xarray.DataArray (x: 2)>
array([0, 2])
Coordinates:
  * x        (x) int64 0 1
