# Notes - Python arrays

## Numeric operation on array

Even though all elements are numeric values in a array, Python doesn't think it is a numeric array. As a result, I cannot do numerical operation in this array. I have to convert the array to a numpy array, so I can do numeric operation.

- **Xarray array computation**
 - https://xarray.pydata.org/en/v2022.03.0/user-guide/computation.html

- **Numpy array nerical operations**
 - Unidata - Numpy Basics, https://unidata.github.io/python-training/workshop/NumPy/numpy-basics/
 - Unidata - Numpy Intermidiate, https://unidata.github.io/python-training/workshop/NumPy/intermediate-numpy/
 - Unidata - Broadcasting and Vectorization, https://unidata.github.io/python-training/workshop/NumPy/numpy-broadcasting-and-vectorization/
 - Numpy basics - https://numpy.org/devdocs/user/absolute_beginners.html
 - Scipy - https://scipy-lectures.org/intro/numpy/operations.html
 
Recommended learning order: (1) Unidata Numpy Basics (2) Numpy basics


## Learning objective
- Create an array with any dimention. Set attributes and coordinates to this array.
- Do numerical operations on this array, and with other arrays.

- broadcasting



## Numpy

In NumPy, dimensions are called **axes**. This means that if you have a 2D array that looks like this:

[0., 0., 0.] \
[1., 1., 1.]

Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3, i.e. matrix(2,3)

In [2]:
import numpy as np

## Create an array and check out its characteristics 

In [3]:
#--- create arrays from a list

a_1d = np.array([1, 2, 3])          # a 1-D array
a_2d = np.array([[1,2,3],[4,5,6]])  # a (2,3) array

#--- create arrays from functions
#      arange(start, stop, interval) creates a range of values in the interval [start,stop) with step spacing.
#      linspace(start, stop, num) creates a range of num evenly spaced values over the range [start,stop].
b_1d_01 = np.arange(3)         # [0 1 2]
b_1d_02 = np.arange(1,4)       # [0 1 2 3]
b_1d_03 = np.arange(1,6,2)     # [1 3 5]

b_1d_11 = np.linspace(1,5,5)   # [1 2 3 4 5], 5 elements
b_1d_12 = np.linspace(1,2,3)   # [1 1.5 2],   3 elements

#--- create n-dimentional arrays
row=5  
col=3
c_nd_01 = np.zeros(row*col).reshape(row,col)
c_nd_02 = np.ones(row*col).reshape(row,col)
c_nd_02 = np.empty(row*col).reshape(row,col)


#--- check out array properties
print(a_2d.ndim)    # See how many dimensions the array has
print(a_2d.shape)   # Print out the shape attribute
print(a_2d.dtype)   # Print out the data type attribute

print(c_nd_01.shape)

2
(2, 3)
int64
(5, 3)


## Adding and sorting elements
https://numpy.org/devdocs/user/absolute_beginners.html#adding-removing-and-sorting-elements

In [4]:
a = np.array([1, 3, 5, 4])
b = np.array([2, 6, 9, 8])

#--- sort array
np.sort(a)

#--- concatenate arrays
np.concatenate((a,b),axis=0)

array([1, 3, 5, 4, 2, 6, 9, 8])

## Convert a 1D array into a 2D array (how to add a new axis to an array)
https://numpy.org/devdocs/user/absolute_beginners.html#how-to-convert-a-1d-array-into-a-2d-array-how-to-add-a-new-axis-to-an-array

In [5]:
#--- use nexaxis 
a1 = np.array([1, 2, 3, 4, 5, 6])
a2 = a[:,np.newaxis]
a3 = a[np.newaxis,np.newaxis,:]

print(a1.shape)
print(a2.shape)
print(a3.shape)

#--- use expand_dims
b1 = np.expand_dims(a, axis=0)
b2 = np.expand_dims(a, axis=1)
print('--------------')
print(b1.shape)
print(b2.shape)

(6,)
(4, 1)
(1, 1, 4)
--------------
(1, 4)
(4, 1)


## Broadcasting

- Unidata - Broadcasting and Vectorization, https://unidata.github.io/python-training/workshop/NumPy/numpy-broadcasting-and-vectorization/
- Numpy - https://numpy.org/devdocs/user/basics.broadcasting.html#basics-broadcasting
- Numpy - https://numpy.org/devdocs/user/absolute_beginners.html#broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

In [44]:
### pairwise addition of two arrays with different dimensions ###

#--- example arrays
a = np.array([1.,2.,3.,4.,5])
b = np.array([10., 20., 30., 40.])

Use loops to add these two arrays

In [47]:
#--- a.shape is a tuple. To convert it to an integer, use a.shape[0]
a_plus_b = np.empty((a.shape[0],b.shape[0]), dtype=a.dtype)

#--- enumerate returns [index, value]
for col, valb in enumerate(b):
  for row, vala in enumerate(a):
    a_plus_b[row, col] = vala + valb

a_plus_b

array([[11., 21., 31., 41.],
       [12., 22., 32., 42.],
       [13., 23., 33., 43.],
       [14., 24., 34., 44.],
       [15., 25., 35., 45.]])

Use newaxis

In [54]:
#--- add two 1-D arrays

a_plus_b = a + b[:, np.newaxis]   # original array values are on rows
print(a_plus_b)

b_plus_a = b + a[:, np.newaxis]   
print(b_plus_a)

[[11. 12. 13. 14. 15.]
 [21. 22. 23. 24. 25.]
 [31. 32. 33. 34. 35.]
 [41. 42. 43. 44. 45.]]
[[11. 21. 31. 41.]
 [12. 22. 32. 42.]
 [13. 23. 33. 43.]
 [14. 24. 34. 44.]
 [15. 25. 35. 45.]]


In [65]:
#--- add multiple n-D arrays
x = np.array([1, 2])
y = np.array([3, 4, 5])
z = np.array([6, 7, 8, 9])

d_2d = x[:, np.newaxis]**2 + y**2  # (row=2, columne=3) array
print("d_2d")
print(d_2d)

d_3d = d_2d[..., np.newaxis] + z
print("")
print("d_3d")
print(d_3d)
print(d_3d.shape)

d_2d
[[10 17 26]
 [13 20 29]]

d_3d
[[[16 17 18 19]
  [23 24 25 26]
  [32 33 34 35]]

 [[19 20 21 22]
  [26 27 28 29]
  [35 36 37 38]]]
(2, 3, 4)


## Exercise 1: Given the 3D temperature field and 1-D pressure coordinates, calculate: 𝑇∗𝑒𝑥𝑝(𝑃/1000) 

## Exercise 2: Given the 2D surface pressure and two 1-D  hybrid coefficients (pk, bk), calculate pressure at each level: P=pk+bk*ps